title: Saptak Banerjee
theme: minima
layouts_dir: _layouts
exclude:
  - LICENSE
  - resume.pdf
description: Software · Quant · Notes
url: "https://nilarkian.github.io"
baseurl: "/Saptak"
markdown: kramdown
permalink: pretty
include:
  - notes


collections:
  writing:
    output: true
    permalink: /writing/:name/
 